name: Docker Image (igot)

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  ghcr_publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log-in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push igot
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/igot:latest
